package org.example.java_base_test.io.nio.show_multi_agent;

class Part7_SelectionKeyEvents {

    static void explain() {
        System.out.println("【第七部分：SelectionKey 四种事件详解】");
        System.out.println();
        System.out.println("═══ 📮 生活场景：快递驿站的四种状态通知 ═══");
        System.out.println();
        System.out.println("  把 NIO Server 想象成一个快递驿站，SelectionKey 的四种事件就是：");
        System.out.println();
        System.out.println("  OP_ACCEPT（有新快递到站需要签收）");
        System.out.println("    驿站大门口来了一辆快递车（新的TCP连接请求）");
        System.out.println("    驿站老板（ServerSocketChannel）要出来签收（accept()）");
        System.out.println("    签收后，这个包裹变成一个独立的格子（SocketChannel）");
        System.out.println();
        System.out.println("  OP_CONNECT（客户连线成功通知）");
        System.out.println("    你主动打电话给驿站预约（connect()），");
        System.out.println("    驿站接通了，你收到通知（finishConnect()确认）");
        System.out.println("    ⚠️ 必须打这个确认电话，否则通话建立不完整");
        System.out.println();
        System.out.println("  OP_READ（格子里有包裹可以取了）");
        System.out.println("    「您有一个包裹，可以来取了」（Socket缓冲区有数据）");
        System.out.println("    你去格子里拿（channel.read(buffer)）");
        System.out.println("    ⚠️ 如果 read() 返回 -1，说明快递员「消失了」（对端关闭连接）");
        System.out.println("       必须取消这个格子（key.cancel()）并关闭（channel.close()）");
        System.out.println();
        System.out.println("  OP_WRITE（你的包裹可以寄出去了）= 最容易误用的事件！");
        System.out.println("    「发件窗口有空位，可以过来发快递了」");
        System.out.println("    ⚠️ 陷阱：发件窗口几乎一直有空位！");
        System.out.println("         一直订阅这个通知 = 驿站每秒钟发100条短信骚扰你");
        System.out.println("         导致你的手机（CPU）爆满，100%！");
        System.out.println("    ✅ 正确用法：只有快递太多寄不完（write() 写了一半），");
        System.out.println("               才订阅 OP_WRITE 等空位通知，");
        System.out.println("               寄完立刻取消订阅！");
        System.out.println();
        System.out.println("═══ 以下是技术细节 ═══");
        System.out.println();
        System.out.println("  OP_ACCEPT  = 8   ServerSocketChannel 专用");
        System.out.println("    触发时机：TCP 三次握手完成，有新连接到来");
        System.out.println("    响应：serverChannel.accept() 得到 SocketChannel");
        System.out.println();
        System.out.println("  OP_CONNECT = 4   客户端 SocketChannel 专用");
        System.out.println("    触发时机：非阻塞 connect() 的握手完成");
        System.out.println("    响应：必须调用 channel.finishConnect()");
        System.out.println("    不调用后果：channel 不可用，后续 read/write 报错");
        System.out.println();
        System.out.println("  OP_READ    = 1   最常用");
        System.out.println("    触发时机：Socket 接收缓冲区有数据 / 对端关闭连接");
        System.out.println("    响应：channel.read(buffer)");
        System.out.println("    ⚠️ 返回 -1 = 对端关闭，必须 key.cancel() + channel.close()");
        System.out.println("    ⚠️ 返回 0  = 非阻塞模式下没数据，稍后再来");
        System.out.println();
        System.out.println("  OP_WRITE   = 2   最容易误用！");
        System.out.println("    含义：Socket 发送缓冲区有空间，可以写数据");
        System.out.println();
        System.out.println("    ⚠️ 陷阱：发送缓冲区「几乎一直有空间」");
        System.out.println("       一直注册 OP_WRITE → select() 一直立刻返回 → CPU 100%！");
        System.out.println();
        System.out.println("    ✅ 正确用法：");
        System.out.println("       Step1：正常直接写 channel.write(buf)，不注册 OP_WRITE");
        System.out.println("       Step2：如果 buf.hasRemaining()（没写完，发送缓冲区满了）");
        System.out.println("              → 注册 OP_WRITE，等缓冲区有空间的通知");
        System.out.println("       Step3：OP_WRITE 触发，继续写剩余数据");
        System.out.println("       Step4：写完，立刻取消 OP_WRITE！");
        System.out.println("       代码：");
        System.out.println("         // 增加 OP_WRITE");
        System.out.println("         key.interestOps(key.interestOps() | SelectionKey.OP_WRITE);");
        System.out.println("         // 取消 OP_WRITE（写完后）");
        System.out.println("         key.interestOps(key.interestOps() & ~SelectionKey.OP_WRITE);");
        System.out.println();
        System.out.println("SelectionKey 重要 API：");
        System.out.println("  key.channel()      → 取回关联的 Channel");
        System.out.println("  key.attachment()   → 取出附加对象（如 Session、ByteBuffer）");
        System.out.println("  key.attach(obj)    → 绑定业务对象（NIO 编程传递状态的标准方式）");
        System.out.println("  key.cancel()       → 取消注册，不再监控");
        System.out.println("  key.interestOps()  → 当前注册的感兴趣事件");
        System.out.println("  key.readyOps()     → 当前已就绪的事件");
        System.out.println();
        System.out.println("  ⚠️ selectedKeys() 必须手动 remove()：");
        System.out.println("     Selector 不会自动清理，不 remove → 下次还会触发 → 重复处理");
        System.out.println("     标准写法：");
        System.out.println("       Iterator<SelectionKey> iter = selector.selectedKeys().iterator();");
        System.out.println("       while (iter.hasNext()) {");
        System.out.println("           SelectionKey key = iter.next();");
        System.out.println("           iter.remove(); // ← 必须！");
        System.out.println("           // 处理 key ...");
        System.out.println("       }");
        System.out.println();
        NIODemo.printSeparator();
    }
}

