package org.example.java_base_test.io.nio.show_multi_agent;

class Part2_BIOProblem {

    static void explain() {
        System.out.println("【第二部分：BIO 的根本问题——一连接一线程】");
        System.out.println();
        System.out.println("═══ 🏦 生活场景：想象一家银行网点 ═══");
        System.out.println();
        System.out.println("  BIO 的工作方式 = 老式银行的「一对一服务」：");
        System.out.println();
        System.out.println("  【BIO 模式】");
        System.out.println("  进来1个客户 → 柜台叫一个服务员专门陪着他");
        System.out.println("  进来10个客户 → 派10个服务员，每人盯着一个");
        System.out.println("  进来1000个客户 → 需要1000个服务员！！！");
        System.out.println();
        System.out.println("  问题1【内存不够】：");
        System.out.println("    每个服务员（线程）要占一间休息室（内存 ~1MB 栈）");
        System.out.println("    1000个服务员 = 需要1000间休息室（1GB内存）→ 撑不住");
        System.out.println();
        System.out.println("  问题2【大部分时间在摸鱼】：");
        System.out.println("    99%的时间，服务员坐在那等客户开口（阻塞在 read()）");
        System.out.println("    真正在处理业务的时间 < 1%");
        System.out.println("    1000个服务员，990个在睡觉，10个在干活");
        System.out.println("    还要频繁切换谁来工作（上下文切换开销巨大）");
        System.out.println();
        System.out.println("  【NIO 模式（对比）】");
        System.out.println("  「大堂经理团队」(Selector + Worker线程池) 管理所有客户取号");
        System.out.println();
        System.out.println("  简单场景：1个「大堂经理」(单Selector线程) 管理所有客户");
        System.out.println("    → 既负责叫号又办理业务，简单但无法利用多核CPU");
        System.out.println();
        System.out.println("  生产环境：多个「业务员」(Worker线程池)，每人管理一部分客户");
        System.out.println("    → Boss线程接受连接，Worker线程处理读写，可并行处理");
        System.out.println("    → Netty、现代Tomcat都采用这种主从Reactor模式");
        System.out.println();
        System.out.println("  共同优势：谁的号到了（数据就绪）就叫谁，后台只需少量人员");
        System.out.println("  10个人轻松处理1000个客户！");
        System.out.println();
        System.out.println("═══ 以下是技术代码分析 ═══");
        System.out.println();
        System.out.println("BIO 服务器代码模式（伪代码）：");
        System.out.println();
        System.out.println("  ServerSocket server = new ServerSocket(8080);");
        System.out.println("  while (true) {");
        System.out.println("      Socket socket = server.accept(); // ← 阻塞1：等新连接");
        System.out.println("      // 必须新建线程！否则 accept() 永远不会被再次调用");
        System.out.println("      new Thread(() -> {");
        System.out.println("          InputStream in = socket.getInputStream();");
        System.out.println("          byte[] buf = new byte[1024];");
        System.out.println("          int len;");
        System.out.println("          while ((len = in.read(buf)) != -1) { // ← 阻塞2：等数据");
        System.out.println("              process(buf, len);");
        System.out.println("          }");
        System.out.println("      }).start();");
        System.out.println("  }");
        System.out.println();
        System.out.println("问题分析：");
        System.out.println("  1000个并发连接 → 1000个线程");
        System.out.println("  每个线程默认栈：512KB ~ 1MB");
        System.out.println("  1000个线程内存：500MB ~ 1GB（光内存就撑不住）");
        System.out.println();
        System.out.println("  更大的问题（线程资源浪费 + 上下文切换）：");
        System.out.println("    每个线程 99% 时间在 in.read() 处阻塞，线程资源被白白占用");
        System.out.println("    真正处理业务的时间 < 1%");
        System.out.println("    1000个线程频繁上下文切换的开销 比 实际处理业务 还大");
        System.out.println();
        System.out.println("  实际案例：早期 Tomcat（BIO 模式）");
        System.out.println("    默认 maxThreads = 200");
        System.out.println("    超过 200 个并发请求 → 排队等待 → 高并发直接崩");
        System.out.println();
        System.out.println("  解决方案：IO 多路复用（NIO Selector）");
        System.out.println("    NIO架构：Boss线程（接受连接）+ Worker线程池（处理读写）");
        System.out.println();
        System.out.println("    模式1【单Reactor单线程】：1个线程既accept又读写");
        System.out.println("      → 简单但无法利用多核，性能最低");
        System.out.println();
        System.out.println("    模式2【单Reactor多线程】：1个 Boss + 多个 Worker");
        System.out.println("      → Boss接受连接，分发给Worker的Selector");
        System.out.println("      → Netty默认模式，适合大多数场景");
        System.out.println();
        System.out.println("    模式3【主从Reactor多线程】：多个 Boss + 多个 Worker");
        System.out.println("      → 多个Boss监听不同端口/IP，Accept性能更高");
        System.out.println("      → 适合超高并发（网关、代理服务器）");
        System.out.println();
        System.out.println("    共同优势：轻松处理 10 万并发连接");
        System.out.println("    → 这是 Netty / 现代 Tomcat（NIO 模式）的基础");
        System.out.println();
        NIODemo.printSeparator();
    }
}

