package org.example.java_base_test.io.nio.show_multi_agent;

class Part19_NettyPractice {

    static void explain() {
        System.out.println("【第十九部分：Netty 实战——Echo Server 到 HTTP Server】");
        System.out.println();
        System.out.println("═══ 🏨 生活场景：连锁酒店的标准服务流程 理解Netty实战 ═══");
        System.out.println();
        System.out.println("  把 Netty 服务器想象成一家连锁酒店的运营模式：");
        System.out.println();
        System.out.println("  【Echo Server = 最简单的「回声酒店」】");
        System.out.println("  酒店只有一个服务：客人说什么，前台就复述什么（Echo = 回声）");
        System.out.println("  这是最基础的服务模式，目的是验证整个服务流程通不通");
        System.out.println("  就像学编程时写的第一个「Hello World」程序");
        System.out.println();
        System.out.println("  酒店运营对应 Netty 组件：");
        System.out.println("    大堂经理（BossGroup）：专门负责迎接新客人（accept 新连接）");
        System.out.println("      - 只管「开门迎客、分配房间」，不管具体服务内容");
        System.out.println("      - 通常只需要 1 个大堂经理（BossGroup 线程数 = 1）");
        System.out.println();
        System.out.println("    客房服务员（WorkerGroup）：负责实际服务每位客人");
        System.out.println("      - 每个服务员管理几个客房（每个 EventLoop 管理多个 Channel）");
        System.out.println("      - 客人有需求就服务（read 事件），服务完继续等待下一个需求");
        System.out.println("      - 服务员数量 = CPU核数×2（WorkerGroup 线程数）");
        System.out.println();
        System.out.println("    服务手册（Pipeline）：每个客房都有一套标准服务流程");
        System.out.println("      - 客人说话→翻译（StringDecoder）→服务员理解→回复→翻译（StringEncoder）");
        System.out.println("      - Pipeline 就是这套「服务流程书」，每个步骤是一个 Handler");
        System.out.println();
        System.out.println("  【HTTP Server = 「会处理具体请求」的酒店】");
        System.out.println("  更高级的版本：不只是复述，而是能处理各种具体业务请求");
        System.out.println("    GET /menu → 返回菜单（处理 GET 请求）");
        System.out.println("    POST /order → 下单（处理 POST 请求）");
        System.out.println("  Netty 内置了 HTTP 解码器，把「字节流」翻译成「HTTP请求对象」");
        System.out.println("  你只需要处理业务逻辑，不需要自己解析 HTTP 协议");
        System.out.println();
        System.out.println("  【ChannelFuture = 「快递单号」异步编程模型】");
        System.out.println("  酒店给你下单的快递单号（ChannelFuture）：");
        System.out.println("    sync()：你在前台等，直到快递真的送到（阻塞）");
        System.out.println("    addListener()：留下手机号，货到了打你电话（回调，推荐）");
        System.out.println("    CLOSE 监听器：快递送达后，直接关闭快递单（连接关闭）");
        System.out.println();
        System.out.println("═══ 以下是 Netty 实战代码（含逐行注释）═══");
        System.out.println();

        // ════════════════════════════════════════════════════════════════
        // 第一节：Netty Echo Server（最简单的 Netty 程序）
        // ════════════════════════════════════════════════════════════════
        System.out.println("━━━ 1. Netty Echo Server（完整代码 + 逐行注释）━━━━━━━━━━━━━━");
        System.out.println();
        System.out.println("  // ── 服务端启动类 ──────────────────────────────────────────");
        System.out.println("  public class NettyEchoServer {");
        System.out.println("      public static void main(String[] args) throws Exception {");
        System.out.println();
        System.out.println("          // BossGroup：只处理 accept（通常1个线程就够）");
        System.out.println("          // 类比：前台接待员，只负责开门迎客，登记分配房间");
        System.out.println("          EventLoopGroup boss   = new NioEventLoopGroup(1);");
        System.out.println();
        System.out.println("          // WorkerGroup：处理 read/write/业务（默认 CPU×2）");
        System.out.println("          // 类比：客房服务员，具体服务每个客户");
        System.out.println("          EventLoopGroup worker = new NioEventLoopGroup();");
        System.out.println();
        System.out.println("          try {");
        System.out.println("              ServerBootstrap b = new ServerBootstrap();");
        System.out.println("              b.group(boss, worker)");
        System.out.println("               // 指定服务端 Channel 类型（NIO 模式）");
        System.out.println("               .channel(NioServerSocketChannel.class)");
        System.out.println("               // 服务端 Socket 配置");
        System.out.println("               .option(ChannelOption.SO_BACKLOG, 128)");
        System.out.println("               // 客户端 Channel 配置（每个 accept 的连接都会应用）");
        System.out.println("               .childOption(ChannelOption.SO_KEEPALIVE, true)");
        System.out.println("               // ★ 核心：初始化每个新连接的 Pipeline");
        System.out.println("               .childHandler(new ChannelInitializer<SocketChannel>() {");
        System.out.println("                   @Override");
        System.out.println("                   protected void initChannel(SocketChannel ch) {");
        System.out.println("                       ch.pipeline()");
        System.out.println("                         // 行分隔符拆包（防粘包）");
        System.out.println("                         .addLast(new LineBasedFrameDecoder(1024))");
        System.out.println("                         // 字节转字符串");
        System.out.println("                         .addLast(new StringDecoder(CharsetUtil.UTF_8))");
        System.out.println("                         // 字符串转字节");
        System.out.println("                         .addLast(new StringEncoder(CharsetUtil.UTF_8))");
        System.out.println("                         // 业务 Handler");
        System.out.println("                         .addLast(new EchoServerHandler());");
        System.out.println("                   }");
        System.out.println("               });");
        System.out.println();
        System.out.println("              // 绑定端口，sync() 等待绑定完成（异步 → 同步）");
        System.out.println("              ChannelFuture f = b.bind(8080).sync();");
        System.out.println("              System.out.println(\"Server started on port 8080\");");
        System.out.println();
        System.out.println("              // 等待服务器 Channel 关闭（阻塞 main 线程）");
        System.out.println("              f.channel().closeFuture().sync();");
        System.out.println("          } finally {");
        System.out.println("              // 优雅关闭（等待已提交任务执行完）");
        System.out.println("              boss.shutdownGracefully();");
        System.out.println("              worker.shutdownGracefully();");
        System.out.println("          }");
        System.out.println("      }");
        System.out.println("  }");
        System.out.println();
        System.out.println("  // ── EchoServerHandler ────────────────────────────────────");
        System.out.println("  // SimpleChannelInboundHandler<T> 会自动 release() inbound 的 ByteBuf");
        System.out.println("  // 如果用 ChannelInboundHandlerAdapter，要手动 ReferenceCountUtil.release(msg)");
        System.out.println("  public class EchoServerHandler");
        System.out.println("          extends SimpleChannelInboundHandler<String> {");
        System.out.println();
        System.out.println("      @Override");
        System.out.println("      protected void channelRead0(ChannelHandlerContext ctx,");
        System.out.println("                                  String msg) {");
        System.out.println("          System.out.println(\"收到: \" + msg);");
        System.out.println("          // writeAndFlush = write(msg) + flush()");
        System.out.println("          // write 只是写到 Netty 发送缓冲区，flush 才真正触发写 Socket");
        System.out.println("          ctx.writeAndFlush(msg + \"\\n\"); // 带换行符，客户端能拆包");
        System.out.println("      }");
        System.out.println();
        System.out.println("      @Override");
        System.out.println("      public void channelActive(ChannelHandlerContext ctx) {");
        System.out.println("          // 连接建立时触发");
        System.out.println("          System.out.println(\"新连接：\" + ctx.channel().remoteAddress());");
        System.out.println("      }");
        System.out.println();
        System.out.println("      @Override");
        System.out.println("      public void exceptionCaught(ChannelHandlerContext ctx,");
        System.out.println("                                   Throwable cause) {");
        System.out.println("          // 统一异常处理（不要让异常吃掉，要记日志）");
        System.out.println("          cause.printStackTrace();");
        System.out.println("          ctx.close(); // 关闭连接");
        System.out.println("      }");
        System.out.println("  }");
        System.out.println();

        // ════════════════════════════════════════════════════════════════
        // 第二节：Netty HTTP Server
        // ════════════════════════════════════════════════════════════════
        System.out.println("━━━ 2. Netty HTTP Server（理解 HTTP 协议处理流程）━━━━━━━━━━━━");
        System.out.println();
        System.out.println("  Netty 内置了完整的 HTTP 编解码器，让你轻松实现 HTTP 服务器。");
        System.out.println("  理解这段代码，也能帮你理解 Spring Boot 底层（它底层就是 Netty）");
        System.out.println();
        System.out.println("  // ── HTTP Server 启动 ─────────────────────────────────────");
        System.out.println("  .childHandler(new ChannelInitializer<SocketChannel>() {");
        System.out.println("      protected void initChannel(SocketChannel ch) {");
        System.out.println("          ch.pipeline()");
        System.out.println("            // HTTP 请求解码器：字节 → HttpRequest + HttpContent");
        System.out.println("            .addLast(new HttpRequestDecoder())");
        System.out.println("            // 把多个 HttpContent 合并成一个完整 FullHttpRequest");
        System.out.println("            .addLast(new HttpObjectAggregator(65536))");
        System.out.println("            // HTTP 响应编码器：HttpResponse → 字节");
        System.out.println("            .addLast(new HttpResponseEncoder())");
        System.out.println("            // 支持大文件 chunked 传输");
        System.out.println("            .addLast(new ChunkedWriteHandler())");
        System.out.println("            // 业务 Handler");
        System.out.println("            .addLast(new HttpServerHandler());");
        System.out.println("      }");
        System.out.println("  });");
        System.out.println();
        System.out.println("  // ── HTTP Handler ────────────────────────────────────────");
        System.out.println("  public class HttpServerHandler");
        System.out.println("          extends SimpleChannelInboundHandler<FullHttpRequest> {");
        System.out.println();
        System.out.println("      protected void channelRead0(ChannelHandlerContext ctx,");
        System.out.println("                                  FullHttpRequest request) {");
        System.out.println("          // 获取请求信息");
        System.out.println("          String uri    = request.uri();            // /api/hello");
        System.out.println("          HttpMethod method = request.method();     // GET/POST");
        System.out.println("          String body   = request.content().toString(UTF_8); // 请求体");
        System.out.println();
        System.out.println("          // 构造响应");
        System.out.println("          String responseBody = \"{\\\"msg\\\": \\\"hello\\\"}\";");
        System.out.println("          FullHttpResponse response = new DefaultFullHttpResponse(");
        System.out.println("              HTTP_1_1,");
        System.out.println("              HttpResponseStatus.OK,");
        System.out.println("              Unpooled.copiedBuffer(responseBody, UTF_8)");
        System.out.println("          );");
        System.out.println("          response.headers()");
        System.out.println("              .set(CONTENT_TYPE, \"application/json\")");
        System.out.println("              .setInt(CONTENT_LENGTH, response.content().readableBytes());");
        System.out.println();
        System.out.println("          // 判断是否 keep-alive");
        System.out.println("          boolean keepAlive = HttpUtil.isKeepAlive(request);");
        System.out.println("          if (keepAlive) {");
        System.out.println("              response.headers().set(CONNECTION, KEEP_ALIVE);");
        System.out.println("              ctx.writeAndFlush(response);");
        System.out.println("          } else {");
        System.out.println("              // 非 keep-alive，写完关闭");
        System.out.println("              ctx.writeAndFlush(response).addListener(ChannelFutureListener.CLOSE);");
        System.out.println("          }");
        System.out.println("      }");
        System.out.println("  }");
        System.out.println();

        // ════════════════════════════════════════════════════════════════
        // 第三节：Netty Future 和 Promise（异步编程模型）
        // ════════════════════════════════════════════════════════════════
        System.out.println("━━━ 3. Netty 的异步编程：ChannelFuture & Promise ━━━━━━━━━━━━");
        System.out.println();
        System.out.println("  Netty 所有 IO 操作都是异步的，返回 ChannelFuture。");
        System.out.println();
        System.out.println("  生活类比：网购下单");
        System.out.println("    传统同步：在收银台前等，货没到不能走（线程阻塞）");
        System.out.println("    Netty 异步：下单后立即拿到「快递单号」（ChannelFuture）");
        System.out.println("              你可以继续干别的，货到了系统自动通知你（回调）");
        System.out.println();
        System.out.println("  四种使用方式：");
        System.out.println();
        System.out.println("  // 方式1：sync()——把异步变同步（简单，但会阻塞 EventLoop 线程）");
        System.out.println("  ChannelFuture f = channel.write(msg);");
        System.out.println("  f.sync(); // 阻塞当前线程直到写完");
        System.out.println("  ⚠ 注意：不能在 EventLoop 线程里调 sync()，会死锁！");
        System.out.println();
        System.out.println("  // 方式2：addListener()——回调（推荐，不阻塞）");
        System.out.println("  channel.writeAndFlush(msg).addListener(future -> {");
        System.out.println("      if (future.isSuccess()) {");
        System.out.println("          System.out.println(\"写入成功\");");
        System.out.println("      } else {");
        System.out.println("          future.cause().printStackTrace();");
        System.out.println("          channel.close();");
        System.out.println("      }");
        System.out.println("  });");
        System.out.println();
        System.out.println("  // 方式3：结合 ChannelFutureListener 常量");
        System.out.println("  ctx.writeAndFlush(response)");
        System.out.println("     .addListener(ChannelFutureListener.CLOSE); // 写完关闭连接");
        System.out.println();
        System.out.println("  // 方式4：Promise——可手动设置结果（类似 CompletableFuture）");
        System.out.println("  Promise<String> promise = channel.eventLoop().newPromise();");
        System.out.println("  // 在某个异步操作完成后：");
        System.out.println("  promise.setSuccess(\"result\");");
        System.out.println("  // 等待结果：");
        System.out.println("  String result = promise.sync().get();");
        System.out.println();

        // ════════════════════════════════════════════════════════════════
        // 第四节：Netty 连接池（ChannelPool）
        // ════════════════════════════════════════════════════════════════
        System.out.println("━━━ 4. Netty 连接管理：连接池 & 优雅关闭 ━━━━━━━━━━━━━━━━━━━━");
        System.out.println();
        System.out.println("  RPC 客户端为什么需要连接池？");
        System.out.println("    每次请求都建一个新 TCP 连接：三次握手 ~1ms，太慢");
        System.out.println("    复用连接：只需要一次握手，后续请求直接发数据");
        System.out.println();
        System.out.println("  Netty 连接池（SimpleChannelPool）：");
        System.out.println("    Bootstrap bootstrap = new Bootstrap()...");
        System.out.println("    ChannelPool pool = new SimpleChannelPool(bootstrap,");
        System.out.println("        new AbstractChannelPoolHandler() {");
        System.out.println("            public void channelCreated(Channel ch) {");
        System.out.println("                ch.pipeline().addLast(new MyHandler());");
        System.out.println("            }");
        System.out.println("        }");
        System.out.println("    );");
        System.out.println("    // 从池中借一个 Channel");
        System.out.println("    Future<Channel> future = pool.acquire();");
        System.out.println("    Channel ch = future.sync().get();");
        System.out.println("    ch.writeAndFlush(msg).sync();");
        System.out.println("    pool.release(ch); // ★ 用完必须还！");
        System.out.println();
        System.out.println("  Dubbo / Spring Cloud 的连接池本质上就是这样工作的");
        System.out.println();
        System.out.println("  优雅关闭（生产必备）：");
        System.out.println("    // 不要直接 System.exit()！");
        System.out.println("    // 正确方式：让 EventLoop 处理完当前任务后关闭");
        System.out.println("    bossGroup.shutdownGracefully(0, 5, TimeUnit.SECONDS);");
        System.out.println("    workerGroup.shutdownGracefully(0, 5, TimeUnit.SECONDS);");
        System.out.println("    // 第一个参数 quietPeriod=0：没有新任务时立即关闭");
        System.out.println("    // 第二个参数 timeout=5：最多等 5 秒");
        System.out.println();
        NIODemo.printSeparator();
    }
}

