package org.example.java_base_test.io.nio.show_multi_agent;

class Part13_MistakesAndSelection {

    static void explain() {
        System.out.println("【第十三部分：常见误区 & 选型指南】");
        System.out.println();
        System.out.println("═══ 🔧 生活场景：选对工具，事半功倍 ═══");
        System.out.println();
        System.out.println("  BIO/NIO/Netty 的选择，就像搬家选交通工具：");
        System.out.println();
        System.out.println("  搬一件行李（<100个连接）→ 打车（BIO）最省事");
        System.out.println("    代码简单，够用就行，不要过度设计");
        System.out.println();
        System.out.println("  搬全家（1000+并发连接）→ 叫货拉拉（NIO+Selector）");
        System.out.println("    一辆大货车效率远超打1000辆出租车");
        System.out.println();
        System.out.println("  搬整栋楼的东西（生产级高并发服务）→ 专业搬家公司（Netty）");
        System.out.println("    自己开货拉拉太费心（原生NIO七大坑），交给专业的");
        System.out.println("    Netty帮你搞定：粘包/拆包/心跳/编解码/连接池...");
        System.out.println();
        System.out.println("  常见误区就像「用错了工具」：");
        System.out.println("  ❌ 用大货车搬一件行李（小项目用NIO，代码复杂了结果一点不快）");
        System.out.println("  ❌ 注册了 OP_WRITE 忘取消（相当于叫货拉拉到了不让走，堵路）");
        System.out.println("  ❌ Netty里做阻塞操作（专业搬家工人被你绑在厕所里，全公司停摆）");
        System.out.println();
        System.out.println("═══ 以下是详细误区分析和选型表 ═══");
        System.out.println();

        System.out.println("一、NIO/Selector 编程常见误区");
        System.out.println();
        System.out.println("  误区1：以为 NIO 一定比 BIO 快");
        System.out.println("    真相：连接数少（<100）时，BIO 代码更简单，性能差不多");
        System.out.println("         连接数多（>1000）时，NIO 才有明显优势");
        System.out.println("         本质：BIO 瓶颈是线程数，NIO 瓶颈是 CPU 处理能力");
        System.out.println();
        System.out.println("  误区2：以为 selector.select() 是忙等（CPU spin）");
        System.out.println("    真相：是真正的线程休眠（epoll_wait），该线程不占用 CPU 时间片");
        System.out.println();
        System.out.println("  误区3：OP_WRITE 一直注册");
        System.out.println("    真相：发送缓冲区几乎一直有空间，OP_WRITE 几乎一直就绪");
        System.out.println("         select() 一直立刻返回 → CPU 100%！");
        System.out.println("         正确：只在写不完时注册，写完立刻取消");
        System.out.println();
        System.out.println("  误区4：selectedKeys() 不 remove()");
        System.out.println("    真相：已处理的 key 不自动移除，下次 select() 还会返回");
        System.out.println("         → 同一事件重复处理");
        System.out.println();
        System.out.println("  误区5：FileChannel 以为能注册 Selector");
        System.out.println("    真相：FileChannel 不支持非阻塞模式，不能注册 Selector");
        System.out.println();
        System.out.println("  误区6：transferTo 不写 while 循环");
        System.out.println("    真相：网络场景一次可能传不完，不写 while 会静默丢数据");
        System.out.println();
        System.out.println("  误区7：Netty handler 里做阻塞操作（数据库查询）");
        System.out.println("    真相：会把 EventLoop 线程卡死，整个服务停响");
        System.out.println("         解决：ctx.executor().execute(() → { 阻塞操作 → 回写 })");
        System.out.println("         或用 eventLoop.submit() 提交到业务线程池");
        System.out.println();

        System.out.println("二、CPU 拷贝 vs DMA 拷贝（容易混淆）");
        System.out.println();
        System.out.println("  DMA 拷贝：");
        System.out.println("    执行者 = DMA 控制器（硬件芯片，独立于 CPU）");
        System.out.println("    触发条件 = 必须有硬件设备参与（磁盘、网卡...）");
        System.out.println("    路径 = 硬件设备 ↔ 内存");
        System.out.println();
        System.out.println("  CPU 拷贝：");
        System.out.println("    执行者 = CPU（用 memcpy 搬字节）");
        System.out.println("    触发条件 = 纯内存之间复制，不涉及硬件");
        System.out.println("    路径 = 内存某区域 → 内存另一区域（哪怕都在内核！）");
        System.out.println();
        System.out.println("  ★ 都在内核空间 ≠ 就是 DMA 拷贝！");
        System.out.println("    Linux 2.4 之前，Page Cache → Socket 缓冲区");
        System.out.println("    两者都在内核，但没有硬件参与，只能 CPU memcpy");
        System.out.println("    Linux 2.4+ 用 Scatter/Gather DMA：");
        System.out.println("    CPU 只写一个「去 Page Cache 哪个地址取数据」的描述符");
        System.out.println("    网卡 DMA 控制器自己去 Page Cache 取，CPU 不搬数据");
        System.out.println("    → 真正的「零 CPU 拷贝」");
        System.out.println();

        System.out.println("三、技术选型指南");
        System.out.println();
        System.out.println("  ┌─────────────────────────┬────────────────────────────────────┐");
        System.out.println("  │ 场景                    │ 推荐方案                           │");
        System.out.println("  ├─────────────────────────┼────────────────────────────────────┤");
        System.out.println("  │ 读写本地小文件           │ BufferedInputStream/OutputStream   │");
        System.out.println("  │                         │ 或 Files.readAllBytes（< 64MB）    │");
        System.out.println("  │ 大文件随机读取（GB级）   │ MappedByteBuffer（内存映射）       │");
        System.out.println("  │ 本地文件传输到网络       │ FileChannel.transferTo（零拷贝）   │");
        System.out.println("  │ 自己写 HTTP/TCP 服务     │ Netty（不要用原生NIO，太复杂）     │");
        System.out.println("  │ 微服务 RPC               │ Dubbo/gRPC（底层都是 Netty）       │");
        System.out.println("  │ 消息队列                 │ Kafka（零拷贝+顺序写）             │");
        System.out.println("  │ 高并发 Web 静态资源      │ Nginx（sendfile）                  │");
        System.out.println("  │ 高并发 Web 动态接口      │ Spring Boot（底层 Netty/Undertow）  │");
        System.out.println("  └─────────────────────────┴────────────────────────────────────┘");
        System.out.println();

        System.out.println("四、整体知识体系一张图");
        System.out.println();
        System.out.println("  操作系统内核");
        System.out.println("    │");
        System.out.println("    ├── 阻塞 IO ────────► Java BIO（InputStream/OutputStream）");
        System.out.println("    │                         └─► 传统 Tomcat、早期 Spring");
        System.out.println("    │");
        System.out.println("    ├── IO 多路复用（epoll）→ Java NIO（Selector+Channel+Buffer）");
        System.out.println("    │                         └─► Netty（工业级封装）");
        System.out.println("    │                               └─► Dubbo / gRPC / Kafka Client");
        System.out.println("    │                               └─► Undertow（新版 Tomcat）");
        System.out.println("    │");
        System.out.println("    ├── sendfile 零拷贝 ──► FileChannel.transferTo()");
        System.out.println("    │                         └─► Kafka Broker（消息转发）");
        System.out.println("    │                         └─► Nginx（静态文件）");
        System.out.println("    │");
        System.out.println("    └── mmap 内存映射 ───► MappedByteBuffer");
        System.out.println("                              └─► RocketMQ（CommitLog）");
        System.out.println("                              └─► 大文件随机读取");
        System.out.println();

        System.out.println("五、推荐学习顺序");
        System.out.println();
        System.out.println("  第1周：打好基础");
        System.out.println("    理解用户态/内核态、五种 IO 模型");
        System.out.println("    掌握 InputStream/OutputStream + BufferedInputStream");
        System.out.println("    写一个 BIO 版本的聊天室（感受它的问题）");
        System.out.println();
        System.out.println("  第2周：NIO 核心");
        System.out.println("    Buffer 三指针（flip/clear/compact）");
        System.out.println("    FileChannel 基本操作");
        System.out.println("    Selector + ServerSocketChannel + SocketChannel");
        System.out.println("    用 NIO 重写聊天室（感受差距）");
        System.out.println();
        System.out.println("  第3周：深入 NIO");
        System.out.println("    transferTo 零拷贝（调用链 + 原理）");
        System.out.println("    MappedByteBuffer 内存映射");
        System.out.println("    epoll vs select/poll 区别");
        System.out.println();
        System.out.println("  第4周：Netty 入门");
        System.out.println("    EventLoopGroup / EventLoop");
        System.out.println("    Pipeline + ChannelHandler");
        System.out.println("    ByteBuf vs ByteBuffer");
        System.out.println("    粘包/拆包：LengthFieldBasedFrameDecoder");
        System.out.println("    用 Netty 写一个 echo server");
        System.out.println();
        System.out.println("  第5周：实战");
        System.out.println("    用 Netty 写简单 HTTP 服务器");
        System.out.println("    读 Kafka 源码（FileRecords.writeTo 那几行）");
        System.out.println("    对比 Nginx sendfile on/off 的性能差距");
        System.out.println();
        System.out.println("────────────────────────────────────────────────────────────");
        System.out.println();
    }
}

